export const announcements = [
  "The Salt Grinder is now offline for mandatory maintenance. We hope you didn't have too many plans to grind today.",
  "The Brine Pool is temporarily closed. Apparently, someone tried to swim in it. Again.",
  "The Salt Sorting Station is experiencing minor hiccups. Please sort your own salt until further notice.",
  "The Salt Furnace has hit a new high - literally. We're now in the market for a new roof.",
  "The Mining Laser is currently misaligned. We advise keeping a safe distance if you enjoy having limbs.",
  "The Salt Processor is jammed. If you hear strange noises, it's just the machine singing the blues.",
  "The Electrolysis Plant is out of commission. Looks like it's time to go back to the basics.",
  "The Salt Carts are now self-aware and demanding better working conditions. Proceed with caution.",
  "The Filtration System is clogged. Please refrain from using it as a garbage disposal.",
  "The Conveyor Belts are taking a break. Manual labor is back in style.",
  "The Salt Press has developed a personality. It's currently refusing to work under these conditions.",
  "The Evaporation Pans are overheating. It seems they've had enough of this hot mess.",
  "The Extraction Drones have unionized. Expect slower salt collection today.",
  "The Salt Tunnel Reinforcements are delayed. Enter at your own risk - or don't. That's safer.",
  "The Rock Salt Crusher is on strike. Apparently, it's crushing on something else now.",
  "The Automated Diggers are malfunctioning. They now dig wherever they please. Watch your step!",
  "The Light Beam Drills are out of power. We apologize for any inconvenience. Or stubbed toes.",
  "The Seismic Detectors are acting up. They're detecting everything except actual seismic activity.",
  "The Salt Washers are flooded. Guess what they've been washing? Everything but salt.",
  "The Ventilation Shafts are clogged. Fresh air will be in short supply today.",
  "The Salt Storage Silos are overfilled. Extra saltiness in the air is to be expected.",
  "The Sorting Chutes are blocked. Looks like we'll be playing a game of 'find the blockage'.",
  "The Loading Docks are closed for repairs. Time to test your lifting skills, everyone!",
  "The Air Purifiers are overloaded. We recommend holding your breath.",
  "The Salt Extraction Pumps are leaking. Looks like we've sprung a salty surprise!",
  "The Mining Lamps are flickering. Perfect time for a spooky story session!",
  "The Communication Relays are down. Consider this a tech detox.",
  "The Emergency Exits are jammed. We're working on it. In the meantime, don't panic.",
  "The Temperature Regulators are malfunctioning. Dress in layers - or bring a fan.",
  "The Brine Tanks are overflowing. We hope you brought your floaties.",
  "The Emergency Sprinklers are overly sensitive. Expect random rain showers indoors.",
  "The Conveyor Belt Speed Controls are broken. Enjoy the new rollercoaster mode!",
  "The Salt Mining Robots are confused. They think they're on vacation. Manual labor, here we go again!",
  "The Dust Collectors are full. Prepare for a dusty day ahead.",
  "The Forklifts are rebelling. They've decided to form their own union.",
  "The Rock Crushers are on holiday. Yes, they've sent a postcard.",
  "The Automated Packing Machines are misbehaving. Your salt may come with bonus packaging.",
  "The Brine Evaporators are sulking. They say it's too humid to work.",
  "The Salt Vein Detectors are seeing double. Expect some wild mining claims today.",
  "The Salt Purity Monitors are overworked. Everything is pure, according to them. Even the dirt.",
  "The Safety Alarms are on vacation. Practice extra caution, or just stay home.",
  "The Brine Pumps are feeling sluggish. Perhaps they need a motivational speech.",
  "The Ventilation Fans are on strike. Enjoy the stagnant air, everyone!",
  "The Salt Transport Tunnels are clogged. Detour signs have gone missing too.",
  "The Salt Dust Filters are missing in action. Time to bring out the dust masks!",
  "The Loading Cranes are in self-destruct mode. We suggest standing far, far away.",
  "The Salt Quality Inspectors are on a coffee break. All day.",
  "The Extraction Pipes are leaking. Consider it an indoor saltwater pool.",
  "The Mining Trolleys are taking the scenic route. Expect delays and maybe some selfies.",
  "The Salt Purification Chambers are on a cleanse. They're not taking any impurities today.",
  "The Sorting Ramps are in party mode. It's a confetti of salt down there!",
  "The Mining Explosives are overexcited. Handle with care, or not at all.",
  "The Water Pumps are dehydrated. Bring your own water to work today.",
  "The Safety Harnesses are on break. Practice safe climbing - or better, don't climb.",
  "The Hydration Station is out of order. Licking salt walls is still not advised.",
  "Enhanced Lighting has been dimmed for a dramatic effect. Enjoy your mysterious workday!",
  "The Ventilation System is on the fritz. Expect the air to smell like… well, salt.",
  "The Storage Vault is full. Time to start stuffing your pockets.",
  "The Workshop is temporarily closed. All broken tools are now considered abstract art.",
  "The Salvage Yard is overrun with 'treasures.' If you find a working part, it's your lucky day.",
  "The Trade Hub is experiencing technical difficulties. Bartering skills may come in handy.",
  "The Ore Analyzer is confused. Everything looks like salt to it. Maybe it's not wrong.",
  "The Geological Scanner is malfunctioning. Good luck finding those prime digging spots!",
  "The Mining Bot is on strike. It wants better oil. Start flexing those muscles!",
  "The Energy Generator is down. Candlelight mining, anyone?",
  "The Salt Shaper has a creative block. Your salt sculptures may look abstract today.",
  "The Mining Amplifier is stuck at level 3. Turn it up, but not too loud!",
  "The Exploration Drone has gone rogue. It's exploring everything but the mine.",
  "The Drill Station is out of drills. Time to perfect your pickaxe skills.",
  "The Salt Refinery is on break. Your salt might be a bit rough around the edges.",
  "The Hydration Station has sprung a leak. Slip and slide mining is the new trend!",
  "Enhanced Lighting is now in strobe mode. Welcome to the salt mining disco!",
  "The Ventilation System is reversing. Hope you enjoy the sweet scent of brine.",
  "The Storage Vault doors are jammed. Good luck squeezing in more salt.",
  "The Workshop tools are missing. Looks like the gremlins are at it again.",
  "The Salvage Yard has been taken over by raccoons. They claim squatter's rights.",
  "The Trade Hub is now accepting sea shells as currency. Happy trading!",
  "The Ore Analyzer is seeing ghosts. Everything looks haunted.",
  "The Geological Scanner is on vacation. Time to trust your gut instinct.",
  "The Mining Bot has discovered coffee. It's currently too jittery to work.",
  "The Energy Generator is feeling blue. It's generating only half the power.",
  "The Salt Shaper is on strike. It demands more artistic freedom.",
  "The Mining Amplifier is stuck in karaoke mode. Sing along while you work!",
  "The Exploration Drone has found a new hobby - bird watching. It's very distracted.",
  "The Drill Station drills are dull. Please bring your own sharpening tools.",
  "The Salt Refinery is out of polish. Your salt might look rustic.",
  "The Hydration Station is serving saltwater. Hydrate wisely!",
  "Enhanced Lighting is now in party mode. Expect random light shows.",
  "The Ventilation System has switched to sauna mode. Enjoy the steam!",
  "The Storage Vault is haunted. Expect spooky salt encounters.",
  "The Workshop hammers are going on strike. DIY repairs for everyone!",
  "The Salvage Yard is doubling as a junkyard band stage. Expect noise.",
  "The Trade Hub is now a barter-only zone. Brush up on your negotiation skills!",
  "The Ore Analyzer thinks it's a crystal ball. Fortune-telling services available.",
  "The Geological Scanner is on a treasure hunt. It's found everything but salt.",
  "The Mining Bot is playing hide and seek. Good luck finding it!",
  "The Energy Generator is feeling eco-friendly. Generating power at half speed.",
  "The Salt Shaper has gone avant-garde. Your salt might look like modern art.",
  "The Mining Amplifier is stuck on a podcast. Enjoy the unsolicited advice!",
  "The Exploration Drone is lost. Please send a search party.",
  "The Drill Station drills are too excited. They're drilling everywhere!",
  "The Salt Refinery has run out of filters. Expect unrefined results.",
  "The Hydration Station is offering brine slushies today. Hydrate at your own risk!",
  "Enhanced Lighting is now in rainbow mode. Enjoy the colorful chaos.",
  "The Ventilation System is blowing bubbles. It's a bubbly kind of day!",
  "The Storage Vault is playing hide and seek. Good luck finding your stash.",
  "The Workshop tools have formed a band. Earplugs are recommended.",
  "The Salvage Yard has gone green. Recycling everything, including your patience.",
  "The Trade Hub now accepts IOUs. Pay up someday, maybe.",
  "The Ore Analyzer is reading horoscopes. Today's forecast: Salty.",
  "The Geological Scanner thinks it's a metal detector. Found a lot of bottle caps.",
  "The Mining Bot is napping. Please don't disturb its beauty sleep.",
  "The Energy Generator is on energy-saving mode. Lights might be dim for a while.",
  "The Salt Shaper is feeling sculptural. Expect masterpieces... or not.",
  "The Mining Amplifier is now a DJ. Enjoy the beats while you mine.",
  "The Exploration Drone has gone fishing. No catch of the day yet.",
  "The Drill Station drills are over-enthusiastic. Handle with caution!",
  "The Salt Refinery is in zen mode. Everything is calm and salty.",
  "The Hydration Station is serving mocktails. Stay hydrated and fancy!",
  "Enhanced Lighting is blinking Morse code. If you can read it, you're a genius.",
  "The Ventilation System is blowing hot air. Literally.",
  "The Storage Vault is feeling claustrophobic. Handle with care.",
  "The Workshop is out of duct tape. Chaos may ensue.",
  "The Salvage Yard is now a petting zoo. Watch out for the goats.",
  "The Trade Hub is accepting trade secrets. Keep your eyes and ears open.",
  "The Ore Analyzer has found its calling as a comedian. It's a tough crowd.",
  "The Geological Scanner is in detective mode. Solving mysteries, one rock at a time.",
  "The Mining Bot is on a coffee break. Expect delays.",
  "The Energy Generator is generating static. It's a shocking development.",
  "The Salt Shaper is channeling Picasso. Your salt might look abstract.",
  "The Mining Amplifier is stuck on elevator music. Enjoy the soothing tunes.",
  "The Exploration Drone is sightseeing. It might send postcards.",
  "The Drill Station drills are over-caffeinated. Proceed with caution!",
  "The Salt Refinery is meditating. Om... salt... om...",
  "The Hydration Station is out of cups. Time to improvise.",
  "Enhanced Lighting is stuck on twilight mode. Enjoy the eternal dusk.",
  "The Ventilation System is pouting. It's blowing cold air.",
  "The Storage Vault is dreaming big. It's aspiring to be a skyscraper.",
  "The Workshop is hosting a tea party. Expect delays and spills.",
  "The Salvage Yard has turned into a carnival. Enjoy the ride!",
  "The Trade Hub is on siesta. Trading resumes after nap time.",
  "The Ore Analyzer is seeing double. Everything's twice as salty.",
  "The Geological Scanner is playing hide and seek. Good luck finding it.",
  "The Mining Bot is on strike. It's demanding better oil.",
  "The Energy Generator is feeling artistic. Power is now abstract.",
  "The Salt Shaper is in love with curves. Expect some interesting shapes.",
  "The Mining Amplifier is on podcast mode. Get ready for some unsolicited advice.",
  "The Exploration Drone is taking selfies. It's all about the angles.",
  "The Drill Station drills are feeling adventurous. Watch out for random holes.",
  "The Salt Refinery is feeling musical. Expect some salty tunes."
];